services:
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        image: inception-nginx
        depends_on:
            - wordpress
        networks:
            - frontend
        environment:
            DOMAIN: ${DOMAIN}
        ports:
            - "80:80"
            - "443:443"
        restart: always

    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        image: maria-database
        volumes:
            - db:/var/lib/mysql
        networks:
            - backend
        restart: always
        healthcheck:
            test:
                [
                    "CMD",
                    "/tmp/healthcheck.sh",
                    "--connect",
                    "--innodb_initialized",
                ]
            start_period: 30s
            interval: 30s
            timeout: 5s
            retries: 5
        environment:
            MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MARIADB_DATABASE: wordpress
            MARIADB_USER: wordpress
            MARIADB_PASSWORD_FILE: /run/secrets/db_password
            SOCKET_PATH: /run/mysql/mysql.sock
        secrets:
            - db_root_password
            - db_password

    wordpress:
        build: ./requirements/wordpress
        image: hivesite
        container_name: wp
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        networks:
            - frontend
            - backend
        restart: always
        env_file: .env
        environment:
            PHP_MEMORY_LIMIT: 1G
            WORDPRESS_DB_HOST: mariadb:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
            WORDPRESS_DB_NAME: wordpress
        secrets:
            - db_password

networks:
    frontend:
        driver: bridge
    backend:
        name: hive-network

secrets:
    db_password:
        file: ./requirements/secrets/db_password.txt
    db_root_password:
        file: ./requirements/secrets/db_root_password.txt
    server-certificate:
        file: ./requirements/secrets/jtuomi.hive.fi.pem
    server-key:
        file: ./requirements/secrets/jtuomi.hive.fi-key.pem

volumes:
    wordpress:
    db:
