services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: inception-nginx
    depends_on:
      - wordpress
    networks:
      - frontend
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: maria-database
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/db_root_password
      MARIADB_DATABASE: wp
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: /run/secrets/db_password
      SOCKET_PATH: /run/mysql/mysql.sock
    secrets:
      - db_root_password
      - db_password

  wordpress:
    build: ./requirements/wordpress
    image: hivesite
    container_name: wp
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - frontend
      - backend
    restart: always
    env_file: .env
    environment:
      PHP_MEMORY_LIMIT: 1G
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_DB_NAME: wp
    secrets:
      - db_password

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

secrets:
  db_password:
    file: ./requirements/secrets/db_password.txt
  db_root_password:
    file: ./requirements/secrets/db_root_password.txt
  server-certificate:
    file: ./requirements/secrets/jtuomi.hive.fi.pem
  server-key:
    file: ./requirements/secrets/jtuomi.hive.fi-key.pem

volumes:
  wordpress:
  db:
