services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - frontend
    environment:
      DOMAIN: ${DOMAIN}
    restart: always
    ports:
      - "443:443"

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/db_root_password
      MARIADB_PASSWORD: /run/secrets/db_password
      CREDENTIALS: /run/secrets/credentials
    secrets:
      - db_root_password
      - db_password
      - credentials

  wordpress:
    build: ./requirements/wordpress
    container_name: wp
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - frontend
      - backend
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
      WORDPRESS_ADMIN_PASSWORD: /run/secrets/wp_admin
      CREDENTIALS: /run/secrets/credentials
    secrets:
      - db_password
      - wp_admin
      - credentials

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

secrets:
  credentials:
    file: ../secrets/credentials.txt
  wp_admin:
    file: ../secrets/wp_admin.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  server-certificate:
    file: ../secrets/jtuomi.hive.fi.pem
  server-key:
    file: ../secrets/jtuomi.hive.fi-key.pem

volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/jtuomi/data/wordpress
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/jtuomi/data/mariadb
      o: bind
