services:
  nginx:
    build: req/nginx/.
    container_name: nginx
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
  wordpress:
    build: req/wordpress/.
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wp
    environment:
      PHP_MEMORY_LIMIT: "-1"
  mariadb:
    build: req/mariadb/.
    container_name: mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  frontend:
    driver: bridge
    driver_opts:
        com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend:
    name: hive-network
    external: true
