CREATE DATABASE IF NOT EXISTS wp;
CREATE USER IF NOT EXISTS 'wordpress'@'%' IDENTIFIED BY 'world';
GRANT ALL PRIVILEGES ON `wp`.* TO 'wordpress'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'hello';
ALTER USER 'root'@'%' IDENTIFIED BY 'hello';
FLUSH PRIVILEGES;
